// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

/*
Package personpb is a generated protocol buffer package.

It is generated from these files:
	person.proto

It has these top-level messages:
	Person
	Address
*/
package personpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name      string   `protobuf:"bytes,1,opt,name=name" json:"name"`
	Age       int32    `protobuf:"varint,2,opt,name=age" json:"age"`
	Telephone string   `protobuf:"bytes,3,opt,name=telephone" json:"telephone"`
	Id        string   `protobuf:"bytes,4,opt,name=id" json:"id"`
	Address   *Address `protobuf:"bytes,5,opt,name=address" json:"address"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Address struct {
	Nation   string `protobuf:"bytes,1,opt,name=nation" json:"nation"`
	District string `protobuf:"bytes,2,opt,name=district" json:"district"`
	Street   string `protobuf:"bytes,3,opt,name=street" json:"street"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Address) GetNation() string {
	if m != nil {
		return m.Nation
	}
	return ""
}

func (m *Address) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "personpb.Person")
	proto.RegisterType((*Address)(nil), "personpb.Address")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x4d, 0x6a, 0xc3, 0x30,
	0x10, 0x85, 0x91, 0xff, 0x3d, 0x2d, 0xa5, 0x9d, 0x45, 0x11, 0xa5, 0x0b, 0xe3, 0x95, 0xa1, 0xe0,
	0x45, 0x7b, 0x82, 0xde, 0xa0, 0x08, 0x7a, 0x00, 0x39, 0x1a, 0x12, 0x41, 0x22, 0x09, 0x49, 0x97,
	0xc8, 0xad, 0x83, 0x65, 0x39, 0xd9, 0xbd, 0xef, 0xcd, 0x1b, 0xe6, 0x0d, 0x3c, 0x3b, 0xf2, 0xc1,
	0x9a, 0xd9, 0x79, 0x1b, 0x2d, 0x76, 0x1b, 0xb9, 0x65, 0xbc, 0x32, 0x68, 0xfe, 0x12, 0x20, 0x42,
	0x65, 0xe4, 0x85, 0x38, 0x1b, 0xd8, 0xd4, 0x8b, 0xa4, 0xf1, 0x15, 0x4a, 0x79, 0x24, 0x5e, 0x0c,
	0x6c, 0xaa, 0xc5, 0x2a, 0xf1, 0x13, 0xfa, 0x48, 0x67, 0x72, 0x27, 0x6b, 0x88, 0x97, 0x29, 0xfa,
	0x30, 0xf0, 0x05, 0x0a, 0xad, 0x78, 0x95, 0xec, 0x42, 0x2b, 0xfc, 0x82, 0x56, 0x2a, 0xe5, 0x29,
	0x04, 0x5e, 0x0f, 0x6c, 0x7a, 0xfa, 0x7e, 0x9b, 0xf7, 0xd3, 0xf3, 0xef, 0x36, 0x10, 0x7b, 0x62,
	0xfc, 0x87, 0x36, 0x7b, 0xf8, 0x0e, 0x8d, 0x91, 0x51, 0x5b, 0x93, 0xdb, 0x64, 0xc2, 0x0f, 0xe8,
	0x94, 0x0e, 0xd1, 0xeb, 0x43, 0x4c, 0xa5, 0x7a, 0x71, 0xe7, 0x75, 0x27, 0x44, 0x4f, 0x14, 0x73,
	0xad, 0x4c, 0x4b, 0x93, 0x7e, 0xfe, 0xb9, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x82, 0xe3, 0x78,
	0x03, 0x01, 0x00, 0x00,
}
